### ISSUE TITLE
 CallDuplexConsensusReads Raw Reads Filtered Due to Not Enough Reads

### ISSUE THREAD

**Issue by doranlab** [fulcrumgenomics/fgbio#556] opened 2019-12-10 01:16 UTC
Hello,

We are playing around with our endogenous UMI content and length and and we created the attached bam files and now we are getting an issue with CallDuplexConsensusReads which states "Raw Reads Filtered Due to Not Enough Reads (Either Total, AB, or BA): 45,386,024 (1.0000)". The only change has been in the UMI content. Is there an email I can send the original and new bam files after they have been processed through GroupReadsByUmi to help us understand why everything is filtered now? I have attached an example of reads at a specific location with the original and modified UMIs.
[exampleumi.original.txt](https://github.com/fulcrumgenomics/fgbio/files/3942536/exampleumi.original.txt)
[example.umi.new.txt](https://github.com/fulcrumgenomics/fgbio/files/3942537/example.umi.new.txt)

Version: fgbio-0.5.0
Commands: 
/usr/bin/java -XX:ParallelGCThreads=1 -jar /apps/fgbio/fgbio-0.5.0.jar GroupReadsByUmi 
--min-map-q=20 
-s paired 
-i aligned.paired-umi.bam 
-t RX 
-o aligned.umi-grouped.bam 
-f counts

/usr/bin/java -XX:ParallelGCThreads=1 -jar /apps/fgbio/fgbio-0.5.0.jar CallDuplexConsensusReads 
-i aligned.umi-grouped.bam 
-o consensus.umi.bam 
--error-rate-post-umi=30 
-m 30

I have looked at another question on this topic here https://github.com/fulcrumgenomics/fgbio/issues/399 but I don't think we are having the same issue. 

Thank you,

Lauryn

**Comment by nh13** [comment] 2019-12-10 01:36
@doranlab nothing looks obvious from the example besides there only being `/B` reads (where are the `/A`?).  I think you're 80% of the way to creating a good test case.  Could you find a family  (ex. `1000006`) where you could attach the SAM file (header included) for the original and new UMIs? For example, for each of the input BAM files:
```bash
samtools view -H <in.bam> > test-case.sam
samtools view <in.bam> | fgrep "MI:Z:1000006" >> test-case.sam
java -jar fgbio.jar CallDuplexConsensusReads -i test-case.sam -o consensus.sam -error-rate-post-umi=30 -m 30
```

Also, version `0.5.0` was released in February of 2018, so almost two years old.  Could you try the [latest release](https://github.com/fulcrumgenomics/fgbio/releases) when you run your test case?

**Comment by doranlab** [comment] 2019-12-11 00:05
Hi Nils,

Thank you for your help, your comment helped me to troubleshoot the results. The way we were extracting the UMIs were resulting in different families for the A strand and B strand groups which then obviously resulted in zero consensus reads. 

Thanks,
Lauryn

**Closed** 2019-12-11 00:20 UTC
Labels: question

**Comment by fgvieira** [comment] 2020-02-03 14:34
@doranlab, could you elaborate on what was your issue? I am having similar problems with `fgbio`. 

@nh13 Right now, I am
- extracting UMIs (in-house script)
- correcting UMIs (`fgbio CorrectUmis`)
- Fix Mate info (`gatk FixMateInformation`)

and I get a BAM file like:
```
A01059:73:H1T3TDRXX:1:1101:32967:1344   163     17      62009535        60      141M    =       62009545        153     CCTCGTCGTGGGTTCTGTACCTGAGAGCAGCAGCAGCAACGCCACCATCCAGTGGCTGGGCACAGGAGACAACGCCAGCCTGGCCATGGTCACCGCTCTGTCCCCGACCCCAAACCCGTGACAACGTCCGAGGCTCCTTGG      FFFFFFFFF:FFFFFFFF:F:FFFFFFFFFF,FFFFFFFFFF:FFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFF:FFF:FF:F,:FF:FFFFFFFFFFFFFFFF:FFFFFF:F,FFFFFF:FFFFFF:F:FFFFF:,FFF   MC:Z:143M MD:Z:141 RG:Z:SAMPLE1     NM:i:0  MQ:i:60 AS:i:141        XS:i:19 OX:Z:NAGCGTA-AAGACAT    RX:Z:TAGCGTA-AAGACAA
A01059:73:H1T3TDRXX:1:1101:32967:1344   83      17      62009545        60      143M    =       62009535        -153    GGTTCTGTACCTGAGAGCAGCAGCAGCAACGCCACCATCCAGTGGCTGGGCACAGGAGACAACGCCAGCCTGGCCATGGTCACCGCTCTGTCCCCGACCCCAAACCCGTGACAACGTCCGAGGCTCCTTGGAGGAAAACGTGT    FFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFF,FFFFFFFF:FFFFF:FFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFF:FF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFF MC:Z:141M MD:Z:143 RG:Z:SAMPLE1     NM:i:0  MQ:i:60 AS:i:143        XS:i:19 OX:Z:AAGACAT-NAGCGTA    RX:Z:AAGACAA-TAGCGTA
```

then I group the reads by UMI (`fgbio GroupReadsByUmi --strategy Paired --input $SAMPLE.cUMI.sorted.bam --family-size-histogram $SAMPLE.cUMIgrp.fam_size_hist --raw-tag RX --assign-tag MI --min-map-q 30 --edits 0 --output $SAMPLE.cUMIgrp.bam`):
```
A01059:73:H1T3TDRXX:1:1101:32967:1344   83      17      62009545        60      143M    =       62009535        -153    GGTTCTGTACCTGAGAGCAGCAGCAGCAACGCCACCATCCAGTGGCTGGGCACAGGAGACAACGCCAGCCTGGCCATGGTCACCGCTCTGTCCCCGACCCCAAACCCGTGACAACGTCCGAGGCTCCTTGGAGGAAAACGTGT    FFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFF,FFFFFFFF:FFFFF:FFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFF:FF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFF MC:Z:141M MD:Z:143 RG:Z:SAMPLE1     MI:Z:13390857/B NM:i:0  MQ:i:60 AS:i:143        XS:i:19 OX:Z:AAGACAT-NAGCGTA    RX:Z:AAGACAA-TAGCGTA
A01059:73:H1T3TDRXX:1:1101:32967:1344   163     17      62009535        60      141M    =       62009545        153     CCTCGTCGTGGGTTCTGTACCTGAGAGCAGCAGCAGCAACGCCACCATCCAGTGGCTGGGCACAGGAGACAACGCCAGCCTGGCCATGGTCACCGCTCTGTCCCCGACCCCAAACCCGTGACAACGTCCGAGGCTCCTTGG      FFFFFFFFF:FFFFFFFF:F:FFFFFFFFFF,FFFFFFFFFF:FFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFF:FFF:FF:F,:FF:FFFFFFFFFFFFFFFF:FFFFFF:F,FFFFFF:FFFFFF:F:FFFFF:,FFF   MC:Z:143M MD:Z:141 RG:Z:SAMPLE1     MI:Z:13390857/B NM:i:0  MQ:i:60 AS:i:141        XS:i:19 OX:Z:NAGCGTA-AAGACAT    RX:Z:TAGCGTA-AAGACAA
```
Why are both reads `/B`? Shouldn't one be `\A` and the other `\B`?

And when i call the consensus (`fgbio CallDuplexConsensusReads --input $SAMPLE.cUMIgrp.bam --min-input-base-quality 10 --min-reads 1 --output $SAMPLE.cUMIcons.bam`), almost all my reads are filtered-out:
```
[2020/02/03 15:17:25 | CallDuplexConsensusReads | Info] Total Raw Reads Considered: 104,034,700.
[2020/02/03 15:17:25 | CallDuplexConsensusReads | Info] Raw Reads Filtered Due to Mismatching Cigars: 140 (0.0000).
[2020/02/03 15:17:25 | CallDuplexConsensusReads | Info] Raw Reads Filtered Due to Not Enough Reads (Either Total, AB, or BA): 103,957,720 (0.9993).
[2020/02/03 15:17:25 | CallDuplexConsensusReads | Info] Raw Reads Filtered Due to Being Fragment/Non-Paired Reads: 0 (0.0000).
[2020/02/03 15:17:25 | CallDuplexConsensusReads | Info] Consensus reads emitted: 12,580.
[2020/02/03 15:17:25 | FgBioMain | Info] CallDuplexConsensusReads completed. Elapsed time: 4.71 minutes.
```

I think it is because I only have ether `/A` or `/B` read groups, but why?
thanks,

**Comment by doranlab** [comment] 2020-02-04 22:37
Hi fgvieira,

I figured out that the way i was pulling my umis was resulting in two different UMI families that should have been identified in the same group, so i was ending up with only /A reads. I suggest going back to your extraction logic and make sure your umis are going to match. I did this by taking the read ID of one of my /A reads and looking for the Read 2 in the original Fastq and using my extraction logic, seeing what i would get, which in my case did not match due to length differences. 

Hope that helps!

Thanks,
Lauryn

**Comment by ARE4S** [comment] 2022-10-26 13:53
Hello everyone,

I'd like to call Duplex Consensus reads using fgbio as well. Unfortunately, I'm facing the exact same issue as mentioned above.

The samples I'm using are paired end sequenced and tagged with 6bp UMI and 11bp stem resulting in a cigar like 6M11S+T 6M11S+T.
Afterwards, I'm extracting UMIs with fgbio-2.0.2 ExtractUmisFromBam, followed by GroupReadsByUmi and CallDuplexConsensusReads
`java -jar fgbio-2.0.2.jar ExtractUmisFromBam \
-i /path_unmapped.bam \
-o /path_unmapped_umi_extracted.bam \
-r 6M11S+T 6M11S+T \
--molecular-index-tags=ZA ZB \
--single-tag=RX`

`java -jar fgbio-2.0.2.jar GroupReadsByUmi \
--input=/path_umi_extracted_aligned_merged_filtered.bam --output=/path_umi_grouped.bam \
--strategy=paired --edits=1`

`java -jar fgbio-2.0.2.jar CallDuplexConsensusReads \
--input=/path_umi_grouped.bam --output=/path_consensus_unmapped.bam \
--error-rate-post-umi 30 --error-rate-pre-umi 45 \
--min-input-base-quality=20`

This leads to the following outputs (examplary Read-ID extracted)

original fastq read 1:
`@M01950:199:000000000-CN4MR:1:1106:27160:16985 1:N:0:2
CACAGGAGTAGCTCAAGAGCTCGTCTGGTAACTATCCATATATGAATAGCCCATTATGGACTCGGGTGAGCTGGTATAGGGGTCTGGGTACTCAGACTTGATGGCCCGGCTAGGAAAGTGGCCATATGTTTGGTAACCTTGCAGGCTGCCG
+
CCCCCCFCFFFFGGGGGGGGGGGGGHGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGGGHGHGHHHHGHHHHHHGGGHHHHHHHHHHHHHHHHHHHHHHHGGGGGHHHHHHHHHGHHFHHHHHHHGFFHHHHHHHHHHGHHGHG`

original fastq read 2:
`@M01950:199:000000000-CN4MR:1:1106:27160:16985 2:N:0:2
TTGAACTCAGTAGCTCACAAAACATCCACTCTGCCTCCAAAGGCCTACCTCTGAACCATGCTGCCTTGCCTCCTACAGACTATGACAGAAGTCCCTTTGTAACATCCCCCATTAGCATGACAATGCCCCCTCACGGCAGCCTGCAAGGTT
+
CCCCCFFFFFFFGGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHGHHHGFGHHHHHHHHGGGGHHHHHGHHHHHHGGHHGGGGHHHGGGGGHHHHHGHGHH`

bam-file reads after UMI extraction:
`M01950:199:000000000-CN4MR:1:1106:8824:16985+CACAGGTTGAAC	163	chr1	200048348	60	133M	=	200048464	250	CAAAACATCCACTCTGCCTCCAAAGGCCTACCTCTGAACCATGCTGCCTTGCCTCCTACAGACTATGACAGAAGTCCCTTTGTAACATCCCCCATTAGCATGACAATGCCCCCTCACGGCAGCCTGCAAGGTT	GGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHGHHHGFGHHHHHHHHGGGGHHHHHGHHHHHHGGHHGGGGHHHGGGGGHHHHHGHGHH	ZA:Z:CACAGG	ZB:Z:TTGAAC	MC:Z:134M	MD:Z:133	RG:Z:A	NM:i:0	MQ:i:60	UQ:i:0	AS:i:133RX:Z:CACAGG-TTGAAC`
`M01950:199:000000000-CN4MR:1:1106:8824:16985+CACAGGTTGAAC	83	chr1	200048464	60	134M	=	200048348	-250	CGGCAGCCTGCAAGGTTACCAAACATATGGCCACTTTCCTAGCCGGGCCATCAAGTCTGAGTACCCAGACCCCTATACCAGCTCACCCGAGTCCATAATGGGCTATTCATATATGGATAGTTACCAGACGAGCT	GHGHHGHHHHHHHHHHFFGHHHHHHHFHHGHHHHHHHHHGGGGGHHHHHHHHHHHHHHHHHHHHHHHGGGHHHHHHGHHHHGHGHGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGHGGGGGGGG	ZA:Z:CACAGG	ZB:Z:TTGAAC	MC:Z:133M	MD:Z:134	RG:Z:A	NM:i:0	MQ:i:60	UQ:i:0	AS:i:134RX:Z:CACAGG-TTGAAC`

grouped reads:
`M01950:199:000000000-CN4MR:1:1106:8824:16985+CACAGGTTGAAC	83	chr1	200048464	60	134M	=	200048348	-250	CGGCAGCCTGCAAGGTTACCAAACATATGGCCACTTTCCTAGCCGGGCCATCAAGTCTGAGTACCCAGACCCCTATACCAGCTCACCCGAGTCCATAATGGGCTATTCATATATGGATAGTTACCAGACGAGCT	GHGHHGHHHHHHHHHHFFGHHHHHHHFHHGHHHHHHHHHGGGGGHHHHHHHHHHHHHHHHHHHHHHHGGGHHHHHHGHHHHGHGHGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGHGGGGGGGG	ZA:Z:CACAGG	ZB:Z:TTGAAC	MC:Z:133M	MD:Z:134	RG:Z:A	MI:Z:6968/B	NM:i:0	MQ:i:60	UQ:i:0	AS:i:134	RX:Z:CACAGG-TTGAAC`
`M01950:199:000000000-CN4MR:1:1106:8824:16985+CACAGGTTGAAC	163	chr1	200048348	60	133M	=	200048464	250	CAAAACATCCACTCTGCCTCCAAAGGCCTACCTCTGAACCATGCTGCCTTGCCTCCTACAGACTATGACAGAAGTCCCTTTGTAACATCCCCCATTAGCATGACAATGCCCCCTCACGGCAGCCTGCAAGGTT	GGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHGHHHGFGHHHHHHHHGGGGHHHHHGHHHHHHGGHHGGGGHHHGGGGGHHHHHGHGHH	ZA:Z:CACAGG	ZB:Z:TTGAAC	MC:Z:134M	MD:Z:133	RG:Z:A	MI:Z:6968/B	NM:i:0	MQ:i:60	UQ:i:0	AS:i:133	RX:Z:CACAGG-TTGAAC`

For this exemplary MI-tag, I don't get any /A reads at all. This is the case for 99% of the reads, where there are either only /A or only /B, but not both at the same time. I think therefore I'm not able to call Duplex Consensus reads. After going through the entire data, I'm still not able to figure out where the issue is located.

I would appreciate any help solving this!
Thank you in advance

**Comment by nh13** [comment] 2022-10-26 14:09
@ARE4S please open a new issue
